import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import SupabaseProvider from "@/Providers/SupabaseProvider";
import UserProvider from "@/Providers/UserProvider";
import ModalProvider from "@/Providers/ModalProvider";
import ToasterProvider from "@/Providers/ToasterProvider";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify-Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        {/* <SupabaseProvider>
          <UserProvider>
            <ModalProvider>
            <Sidebar>{children}</Sidebar>
            </ModalProvider>
          </UserProvider>
        </SupabaseProvider> */}
        <ToasterProvider />

        <SupabaseProvider>
          <UserProvider>
            <ModalProvider/>
              <Sidebar>{children}</Sidebar>
          
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
